### ISSUE TITLE
[Question] Expired JWT on active GetMessages stream

### ISSUE THREAD

**Issue by arxdeus** [ArtyomArtamonov/msg#7]
Hi, what we should do if our `message.MessageService.GetMessage` stream returned `16 UNAUTHENTICATED: JWT is expired`

I mean, if we need reconnect to stream every `${JWT_DURATION_MIN}` minutes, then that means that we will lose one message every 15 minutes when our stream will signal us that our token has expired? 
And we will send `auth.AuthService.Refresh` request, and then reconnect to stream?

Doesn't this's overhead solution? I mean, i can't understand this algorithm well, cuz that means we will have a lot of requests to our server

Will be glad to hear your opinion to that question.

**Comment by ArtyomArtamonov** [comment]
Hi. Thanks for asking. 
The idea was to delegate this process to client. When stream returns  `16 UNAUTHENTICATED: JWT is expired`, client should refresh his token and connect again. Then client should get all messages that were not handled by stream.
If we don't check for access token, imagine one of this token gets hijacked. Then the hacker could read all messages of another client indefinitely. 

As you can see, this application consists of two microservices: api and message. API part handles all grpc unary operations. Message part handles stream that sends client his messages in real time. I chose this option in order to verically scale in the future. Dividing stateful and stateless parts might help creating replicas of each part. But if I had chosen monolitic architecture, I could not then create replicas of this application because of stateful part [repository.SessionStore](https://github.com/ArtyomArtamonov/msg/blob/98550de8495baddea2f83bd21e4e16539bc78f2f/internal/repository/session_store.go#L23)

Anyway, if you have any suggestions, feel free to write them here. For now, this issue should be closed
